---
-   hosts: docker-registries
    vars_files: 
    -   vars.yml
    remote_user: ansible
    sudo: yes


    tasks:
    -   name: Downloading and enable the EPEL repository definitions.
        yum: name=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm state=present

    -   name: ensure app dependencies are installed for docker-registry
        yum: name={{ item }} state=installed
        with_items: ${system_packages}
    
    -   name: get docker-registry repo
        git: repo=https://github.com/dotcloud/docker-registry.git dest={{ project_root }}/docker-registry/

    -   name: use sample docker-registry config
        shell: chdir={{ project_root }}docker-registry/config/ cp config_sample.yml config.yml

    -   name: Install python packages
        pip: requirements={{ py_requirements }}
    
    -   name: write gunicorn init script
        template: src=./gunicorn-upstart.conf.j2 dest=/etc/init/gunicorn-{{ host }}.conf
        notify:
            - restart gunicorn

#    -   name: Let inotify know about the new init conf
#        action: shell touch /etc/init/*

    -   name: restart gunicorn
        service:  name=gunicorn-{{ host }} state=restarted


    handlers:
    -   include: handlers.yml
